# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textChecker', '0003_auto_20170308_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StringText',
        ),
    ]
